"""0001_form_config

Revision ID: 45c82302f464
Revises:
Create Date: 2026-01-05 18:12:42.588605

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "45c82302f464"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_config",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=False),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("changed_on", sa.DateTime(), nullable=False),
        sa.Column("created_by_fk", sa.Integer(), nullable=False),
        sa.Column("changed_by_fk", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["changed_by_fk"],
            ["ab_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_fk"],
            ["ab_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_config")
    # ### end Alembic commands ###
