"""0002_form_reponse

Revision ID: 60190cbc744b
Revises: 45c82302f464
Create Date: 2026-03-19 17:18:33.282363

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "60190cbc744b"
down_revision = "45c82302f464"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_responses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("form_config_id", sa.String(length=36), nullable=False),
        sa.Column("responses", sa.JSON(), nullable=False),
        sa.Column("submitted_at", sa.DateTime(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["form_config_id"], ["form_config.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("form_responses")
    # ### end Alembic commands ###
